// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"


namespace BAGameplayTags
{
	/* Input Tags */
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnEquipAxe);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);


	/* Player Tags */
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UneEquip_Axe);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	/* Event Tags */
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnEquip_Axe);

	BOSSARENA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	
}
